### ISSUE TITLE
Problems with the Neo client under Ubuntu

### ISSUE THREAD

**Issue by ikomorff** [aydinnyunus/wallet-tracker#3]
Do you have any idea how I can solve the problem with the wallet tracker? I use it under Ubuntu and always get this error message from the Neo client. I have logged in to Neo and also changed the password.

![Bildschirmfoto vom 2024-06-21 08-41-10](https://github.com/aydinnyunus/wallet-tracker/assets/77875587/b03f6a48-fd3f-4ace-aa06-8828ba677fd7)

**Comment by aydinnyunus** [comment]
Hi @ikomorff,

I make some improvements can you try again with the new version ?

**Comment by ikomorff** [comment]
![Bildschirmfoto vom 2024-06-22 18-52-10](https://github.com/aydinnyunus/wallet-tracker/assets/77875587/15ee1631-4e25-452e-88e0-1aa38ca690c2)

**Comment by ikomorff** [comment]
Can you explain to me what I have to set in neo4j in the browser to use the wallet tracker in parallel in the terminal. neo4j in the browser shows me that I am connected.

**Comment by aydinnyunus** [comment]
> ![Bildschirmfoto vom 2024-06-22 18-52-10](https://private-user-images.githubusercontent.com/77875587/342001689-15ee1631-4e25-452e-88e0-1aa38ca690c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMzA4NjUsIm5iZiI6MTcxOTEzMDU2NSwicGF0aCI6Ii83Nzg3NTU4Ny8zNDIwMDE2ODktMTVlZTE2MzEtNGUyNS00NTJlLTg4ZTAtMWFhMzhjYTY5MGMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDA4MTYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYTk5NWZiNDMzZmJkNWEwYzdmYTdiMTVjNGI5ZDk1MzY1Mzc4YmQ3MTAzNGY4YTA2Y2Q5OGQzZTIxN2NmOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JH4qzB1LvSS3_if476OuMOFZn7ZzqILm0oDa2yKfXHk)

Hi again,

You are getting Authentication error because in Golang and Docker environment variables did not match. I create a .env file to use global config for them. You can change the credentials on .env file use them.

**Comment by aydinnyunus** [comment]
> Can you explain to me what I have to set in neo4j in the browser to use the wallet tracker in parallel in the terminal. neo4j in the browser shows me that I am connected.

If you connect to localhost:80 it shows you the dashboard. You can import neodash/dashboard.json to view better dashboard. Also you can start the neodash with `./wallet-tracker neodash start &` to run on background process and then run other wallet-tracker commands.
